export const backupPoliceStations = [
    { id: 1,  name: 'Connaught Place Police Station', area: 'Central Delhi',    address: 'Connaught Place, New Delhi',      lat: 28.6304, lon: 77.2177 },
    { id: 2,  name: 'Karol Bagh Police Station',      area: 'Central Delhi',    address: 'Karol Bagh, New Delhi',           lat: 28.6519, lon: 77.1904 },
    { id: 3,  name: 'Chandni Chowk Police Station',   area: 'Central Delhi',    address: 'Chandni Chowk, Old Delhi',        lat: 28.6506, lon: 77.2303 },
    { id: 4,  name: 'Saket Police Station',            area: 'South Delhi',      address: 'Saket, New Delhi',                lat: 28.5244, lon: 77.2066 },
    { id: 5,  name: 'Dwarka Police Station',           area: 'South West Delhi', address: 'Dwarka Sector 8, New Delhi',      lat: 28.5921, lon: 77.0460 },
    { id: 6,  name: 'Rohini Police Station',           area: 'North West Delhi', address: 'Rohini Sector 7, New Delhi',      lat: 28.7489, lon: 77.0674 },
    { id: 7,  name: 'Mayur Vihar Police Station',      area: 'East Delhi',       address: 'Mayur Vihar Phase 1, New Delhi',  lat: 28.6074, lon: 77.2982 },
    { id: 8,  name: 'Lajpat Nagar Police Station',    area: 'South Delhi',      address: 'Lajpat Nagar, New Delhi',         lat: 28.5678, lon: 77.2436 },
    { id: 9,  name: 'Shahdara Police Station',         area: 'Shahdara',         address: 'Shahdara, Delhi',                 lat: 28.6844, lon: 77.2842 },
    { id: 10, name: 'Vasant Kunj Police Station',      area: 'South West Delhi', address: 'Vasant Kunj, New Delhi',          lat: 28.5218, lon: 77.1584 },
    { id: 11, name: 'Preet Vihar Police Station',      area: 'East Delhi',       address: 'Preet Vihar, New Delhi',          lat: 28.6424, lon: 77.2944 },
    { id: 12, name: 'Hauz Khas Police Station',        area: 'South Delhi',      address: 'Hauz Khas, New Delhi',            lat: 28.5494, lon: 77.2001 },
    { id: 13, name: 'Model Town Police Station',       area: 'North Delhi',      address: 'Model Town, Delhi',               lat: 28.7196, lon: 77.1910 },
    { id: 14, name: 'Janakpuri Police Station',        area: 'West Delhi',       address: 'Janakpuri, New Delhi',            lat: 28.6219, lon: 77.0819 },
    { id: 15, name: 'Nehru Place Police Station',      area: 'South Delhi',      address: 'Nehru Place, New Delhi',          lat: 28.5494, lon: 77.2501 },
];